// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4a0IfpcT2gvwpuCUT2JG_gpko9Lm7AaQ',
    appId: '1:858455283605:android:c3218253778b97b7f8089c',
    messagingSenderId: '858455283605',
    projectId: 'chatapp-bd2b6',
    storageBucket: 'chatapp-bd2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZpiVkjkIsMGjCpPZFuEZGdpnnJpaOenQ',
    appId: '1:858455283605:ios:e41a6800964c631df8089c',
    messagingSenderId: '858455283605',
    projectId: 'chatapp-bd2b6',
    storageBucket: 'chatapp-bd2b6.appspot.com',
    iosClientId: '858455283605-ug9sogjosdrt6nhun5ovh5drgpln27tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
