name: flutter_weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: any
  google_fonts: ^2.1.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
